---
title: "FinalProject"
author: "Gautam Gireesh"
date: "18/08/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(olsrr)
library(rcompanion)
# df<-read.csv("data.csv")
# clean_data<-na.omit(df)
# data_split<-split(clean_data, clean_data$Country)

df<-read.csv("new_Data.csv")
data_split<-split(df, df$Country)
american_data<-rbind(data_split$Canada, data_split$USA)
asian_data<-rbind(data_split$China, data_split$India, data_split$Mongolia, data_split$Pakistan, data_split$Singapore, data_split$`South Korea`, data_split$Taiwan, data_split$UAE)

```

```{r covid hours[AMERICAN]}
covid1 = american_data[,c(3)]
covid2 = american_data[,c(7)]
covid3 = american_data[,c(10)]
covid4 = american_data[,c(13)]

covid_list<-list(covid1, covid2, covid3, covid4)
covid_matrice<-do.call(cbind, covid_list)
covid_average<-rowMeans(covid_matrice, na.rm = TRUE)
covid_mean<-mean(covid_average, na.rm = TRUE)
centered_covid_avg<-covid_average - covid_mean
hist(centered_covid_avg)
```

```{r covid hours[ASIAN]}
asian_covid1 = asian_data[,c(3)]
asian_covid2 = asian_data[,c(7)]
asian_covid3 = asian_data[,c(10)]
asian_covid4 = asian_data[,c(13)]

asian_covid_list<-list(asian_covid1, asian_covid2, asian_covid3, asian_covid4)
asian_covid_matrice<-do.call(cbind, asian_covid_list)
asian_covid_average<-rowMeans(asian_covid_matrice, na.rm = TRUE)
asian_covid_mean<-mean(asian_covid_average, na.rm = TRUE)
asian_centered_covid_avg<-asian_covid_average - asian_covid_mean
hist(asian_centered_covid_avg)
```

```{r quiz score[AMERICAN]}
quiz1 = american_data[,c(5)]
quiz2 = american_data[,c(8)]
quiz3 = american_data[,c(11)]
quiz4 = american_data[,c(14)]
hist(quiz4)

quiz_list<-list(quiz1, quiz2, quiz3)
quiz_matrice<-do.call(cbind, quiz_list)
quiz_average<-rowMeans(quiz_matrice, na.rm = TRUE)
quiz_mean<-mean(quiz_average, na.rm = TRUE)
centered_quiz_avg<-quiz_average - quiz_mean
hist(centered_quiz_avg)
```

```{r quiz score[ASIAN]}
asian_quiz1 = asian_data[,c(5)]
asian_quiz2 = asian_data[,c(8)]
asian_quiz3 = asian_data[,c(11)]
asian_quiz4 = asian_data[,c(14)]
transformed_asian_quiz4 = transformTukey(asian_quiz4, plotit=FALSE)
hist(asian_quiz4)
hist(transformed_asian_quiz4)
asian_quiz_list<-list(asian_quiz1, asian_quiz2, asian_quiz3)
asian_quiz_matrice<-do.call(cbind, asian_quiz_list)
asian_quiz_average<-rowMeans(asian_quiz_matrice, na.rm = TRUE)
asian_quiz_mean<-mean(asian_quiz_average, na.rm = TRUE)
asian_centered_quiz_avg<-asian_quiz_average - asian_quiz_mean
# hist(asian_centered_quiz_avg)
```

```{r stats hours[AMERICAN]}
sta1 = american_data[,c(2)]
sta2 = american_data[,c(6)]
sta3 = american_data[,c(9)]
sta4 = american_data[,c(12)]

sta_list<-list(sta1, sta2, sta3, sta4)
sta_matrice<-do.call(cbind, sta_list)
sta_average<-rowMeans(sta_matrice, na.rm = TRUE)
sta_mean<-mean(sta_average, na.rm = TRUE)
centered_sta_avg<-sta_average - sta_mean
hist(centered_sta_avg)
```

```{r stats hours[ASIAN]}
asian_sta1 = asian_data[,c(2)]
asian_sta2 = asian_data[,c(6)]
asian_sta3 = asian_data[,c(9)]
asian_sta4 = asian_data[,c(12)]

asian_sta_list<-list(asian_sta1, asian_sta2, asian_sta3, asian_sta4)
asian_sta_matrice<-do.call(cbind, asian_sta_list)
asian_sta_average<-rowMeans(asian_sta_matrice, na.rm = TRUE)
asian_sta_mean<-mean(asian_sta_average, na.rm = TRUE)
asian_centered_sta_avg<-asian_sta_average - asian_sta_mean
hist(asian_centered_sta_avg)
```

```{r constructing final data frame}
X <- data.frame(centered_covid_avg, centered_sta_avg, centered_quiz_avg)
Y <- data.frame(quiz4)
```

```{r Analyzing relation between response and explanatory variables [American]}
pairs(~centered_covid_avg + centered_sta_avg + centered_quiz_avg, data = X)
pairs(~asian_centered_covid_avg + asian_centered_sta_avg + asian_centered_quiz_avg, data = X)
```

```{r American models}
n<-length(quiz4)

full_model<-lm(quiz4 ~ centered_covid_avg + centered_sta_avg + centered_quiz_avg, data=american_data)

model1<-lm(quiz4~centered_covid_avg, data=american_data)
p_prime1 <- length(model1$coefficients)
summary(model1)
SSres1<-deviance(model1)
AIC1<-n*log(SSres1) -n*log(n) + 2*p_prime1
print(AIC1)
mallow_cp1<-ols_mallows_cp(model1, full_model)

model2<-lm(quiz4~centered_sta_avg, data=american_data)
p_prime2 <- length(model2$coefficients)
summary(model2)
SSres2<-deviance(model2)
AIC2<-n*log(SSres2) -n*log(n) + 2*p_prime2
print(AIC2)
mallow_cp2<-ols_mallows_cp(model2, full_model)

model3<-lm(quiz4~centered_quiz_avg, data=american_data)
p_prime3 <- length(model3$coefficients)
summary(model3)
SSres3<-deviance(model3)
AIC3<-n*log(SSres3) -n*log(n) + 2*p_prime3
print(AIC3)
mallow_cp3<-ols_mallows_cp(model3, full_model)
layout(matrix(c(1,2,3,4),2,2))
plot(model3)

model4<-lm(quiz4~centered_covid_avg + centered_quiz_avg, data=american_data)
p_prime4 <- length(model4$coefficients)
summary(model4)
SSres4<-deviance(model4)
AIC4<-n*log(SSres4) -n*log(n) + 2*p_prime4
print(AIC4)
mallow_cp4<-ols_mallows_cp(model4, full_model)

model5<-lm(quiz4~centered_sta_avg + centered_quiz_avg, data=american_data)
p_prime5 <- length(model5$coefficients)
summary(model5)
ssres5<-deviance(model5)
aic5<-n*log(ssres5) -n*log(n) + 2*p_prime5
print(aic5)
mallow_cp5<-ols_mallows_cp(model5, full_model)


model6<-lm(quiz4~centered_sta_avg + centered_covid_avg, data=american_data)
p_prime6 <- length(model6$coefficients)
summary(model6)
SSres6<-deviance(model6)
AIC6<-n*log(SSres6) -n*log(n) + 2*p_prime6
print(AIC6)
mallow_cp6<-ols_mallows_cp(model6, full_model)

model7<-lm(quiz4~centered_quiz_avg + centered_covid_avg + centered_sta_avg, data=american_data)
p_prime7 <- length(model7$coefficients)
summary(model7)
SSres7<-deviance(model7)
AIC7<-n*log(SSres7) -n*log(n) + 2*p_prime7
print(AIC7)
mallow_cp7<-ols_mallows_cp(model7, full_model)
```

```{r Asian models}
asian_n<-length(asian_quiz4)

asian_full_model<-lm(asian_quiz4~asian_centered_covid_avg + asian_centered_sta_avg + asian_centered_quiz_avg, data=asian_data)

asian_model1<-lm(asian_quiz4~asian_centered_covid_avg, data=asian_data)
asian_p_prime1 <- length(asian_model1$coefficients)
summary(asian_model1)
asian_SSres1<-deviance(asian_model1)
asian_AIC1<-asian_n*log(asian_SSres1) -asian_n*log(asian_n) + 2*asian_p_prime1
print(asian_AIC1)
asian_mallow_cp1<-ols_mallows_cp(asian_model1, asian_full_model)

asian_model2<-lm(asian_quiz4~asian_centered_sta_avg, data=asian_data)
asian_p_prime2 <- length(asian_model2$coefficients)
summary(asian_model2)
asian_SSres2<-deviance(asian_model2)
asian_AIC2<-asian_n*log(asian_SSres2) -asian_n*log(asian_n) + 2*asian_p_prime2
print(asian_AIC2)
asian_mallow_cp2<-ols_mallows_cp(asian_model2, asian_full_model)

asian_model3<-lm(asian_quiz4~asian_centered_quiz_avg, data=asian_data)
asian_p_prime3 <- length(asian_model3$coefficients)
summary(asian_model3)
asian_SSres3<-deviance(asian_model3)
asian_AIC3<-asian_n*log(asian_SSres3) -asian_n*log(asian_n) + 2*asian_p_prime3
print(asian_AIC3)
asian_mallow_cp3<-ols_mallows_cp(asian_model3, asian_full_model)

asian_model4<-lm(asian_quiz4~asian_centered_covid_avg + asian_centered_quiz_avg, data=asian_data)
asian_p_prime4 <- length(asian_model4$coefficients)
summary(asian_model4)
asian_SSres4<-deviance(asian_model4)
asian_AIC4<-asian_n*log(asian_SSres4) -asian_n*log(asian_n) + 2*asian_p_prime4
print(asian_AIC4)
asian_mallow_cp4<-ols_mallows_cp(asian_model4, asian_full_model)

asian_model5<-lm(asian_quiz4~asian_centered_sta_avg + asian_centered_quiz_avg, data=asian_data)
asian_p_prime5 <- length(asian_model5$coefficients)
summary(asian_model5)
asian_SSres5<-deviance(asian_model5)
asian_AIC5<-asian_n*log(asian_SSres5) -asian_n*log(asian_n) + 2*asian_p_prime5
print(asian_AIC5)
asian_mallow_cp5<-ols_mallows_cp(asian_model5, asian_full_model)
layout(matrix(c(1,2,3,4),2,2))
plot(asian_model5)

asian_model6<-lm(asian_quiz4~asian_centered_sta_avg + asian_centered_covid_avg, data=asian_data)
asian_p_prime6 <- length(asian_model6$coefficients)
summary(asian_model6)
asian_SSres6<-deviance(asian_model6)
asian_AIC6<-asian_n*log(asian_SSres6) -asian_n*log(asian_n) + 2*asian_p_prime6
print(asian_AIC6)
asian_mallow_cp6<-ols_mallows_cp(asian_model6, asian_full_model)

asian_model7<-lm(asian_quiz4~asian_centered_quiz_avg + asian_centered_covid_avg + asian_centered_sta_avg, data=asian_data)
asian_p_prime7 <- length(asian_model7$coefficients)
summary(asian_model7)
asian_SSres7<-deviance(asian_model7)
asian_AIC7<-asian_n*log(asian_SSres7) -asian_n*log(asian_n) + 2*asian_p_prime7
print(asian_AIC7)
asian_mallow_cp7<-ols_mallows_cp(asian_model7, asian_full_model)
```